name: CI

on:
  push:
    branches:
      - testbringup
      - main
      - icon

jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradelw
        run: chmod +x gradlew
      - name: Build debug apk
        run: ./gradlew build
      - uses: actions/upload-artifact@v1
        with:
          name : debug-apk
          path : build/app/outputs/apk/debug/app-debug.apk